# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18134267f96bd0ce43ef3f0afc48a28d60759afec5c2cf825495dde3d098afb93f7721711c0b771c23554aea9e19a36b342db21d3314ab6f9f97aea1569ec64c

test:
  secret_key_base: 41a2fde917b7ed1fce281eed7611e6074f995f98651e15ea27bf09e33a26bad80067c15f34ea41cfcaf6f0502e76c318a895823d3315763f477f77cd2eb5670c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
